// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    [Migration("20251028214024_AggiuntaCitta")]
    partial class AggiuntaCitta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CittaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Citta");
                });

            modelBuilder.Entity("IndirizzoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<int>("LinkCittaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonaEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkCittaId");

                    b.HasIndex("PersonaEntityId");

                    b.ToTable("IndirizzoEntity");
                });

            modelBuilder.Entity("PersonaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persone", (string)null);
                });

            modelBuilder.Entity("IndirizzoEntity", b =>
                {
                    b.HasOne("CittaEntity", "LinkCitta")
                        .WithMany()
                        .HasForeignKey("LinkCittaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonaEntity", null)
                        .WithMany("ListIndirizzi")
                        .HasForeignKey("PersonaEntityId");

                    b.Navigation("LinkCitta");
                });

            modelBuilder.Entity("PersonaEntity", b =>
                {
                    b.Navigation("ListIndirizzi");
                });
#pragma warning restore 612, 618
        }
    }
}
